services:
  postgres:
    image: postgres
    container_name: postgresPortador
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5430:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9020:8080