server:
  port: 9003
spring:
  application:
    name: portador-app

  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://localhost:5430/postgres
    username: admin
    password: senha123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 15
      connection-timeout: 1000
      idle-timeout: 300000
      max-lifetime: 600000
      initialization-fail-timeout: -1
      validation-timeout: 1000
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    openfeign:
      client:
        config:
          creditAnalysis:
            connectTimeout: 3000
            readTimeout: 500
            loggerLevel: BASIC
            dismiss404: true

url:
  creditanalysis.host: localhost:9001/v1.0/credits/analysis
